// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: post_tags.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createPostTag = `-- name: CreatePostTag :one
INSERT INTO post_tags (
	post_id, tag_id
) VALUES ( $1, $2 ) RETURNING id, post_id, tag_id
`

type CreatePostTagParams struct {
	PostID uuid.UUID `json:"postId"`
	TagID  uuid.UUID `json:"tagId"`
}

func (q *Queries) CreatePostTag(ctx context.Context, arg CreatePostTagParams) (PostTag, error) {
	row := q.db.QueryRowContext(ctx, createPostTag, arg.PostID, arg.TagID)
	var i PostTag
	err := row.Scan(&i.ID, &i.PostID, &i.TagID)
	return i, err
}
