// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package internal

import (
	"database/sql"

	"github.com/google/uuid"
)

type Category struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

type Post struct {
	ID          uuid.UUID      `json:"id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	CategoryID  uuid.NullUUID  `json:"categoryId"`
	Path        sql.NullString `json:"path"`
	Status      sql.NullString `json:"status"`
	CreatedAt   sql.NullTime   `json:"createdAt"`
	UpdatedAt   sql.NullTime   `json:"updatedAt"`
}

type PostTag struct {
	ID     uuid.UUID `json:"id"`
	PostID uuid.UUID `json:"postId"`
	TagID  uuid.UUID `json:"tagId"`
}

type Tag struct {
	ID   uuid.UUID      `json:"id"`
	Name sql.NullString `json:"name"`
}
